os: linux
dist: xenial
language: node_js
node_js:
  - "13.7.0"

cache: npm

before_script:
  - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p  

script:
  - bash ./scripts/run_tests.sh 