sudo: required
language: node_js
node_js:
  - "13.7"
cache:
  directories:
  - node_modules
install:
  - npm install -g truffle
  - npm install -g ganache-cli
  - npm install
before_script:
  - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
script:
  - ganache-cli --networkId 1337 --chainId 1337
  - sleep 10
  - node_modules/.bin/gsn start
  - sleep 10
  - truffle test